#!/bin/sh

git checkout gh-pages
git checkout master .
git reset HEAD
make html -C doc/
mv -fv doc/_build/html/* ./
git add -A
git commit -m "Autogenerated gh-pages for `git log master -1 --pretty=short --abbrev-commit`" 
git push origin gh-pages 
git checkout master

 
